/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DayList: typeof import('./src/components/day-list/index.vue')['default']
    FloatTabbar: typeof import('./src/components/float-tabbar/index.vue')['default']
    List: typeof import('./src/components/day-list/list.vue')['default']
    ListItem: typeof import('./src/components/day-list/list-item.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionDate: typeof import('./src/components/day-list/selectionDate.vue')['default']
  }
}
